"""Add file_path and fields to Template

Revision ID: 37f9dfd4b821
Revises: 16b91d71d45a
Create Date: 2026-02-22 07:22:57.831228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f9dfd4b821'
down_revision: Union[str, None] = '16b91d71d45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
